# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/example-nbdev',
                'doc_host': 'https://damc-dev.github.io',
                'git_url': 'https://github.com/damc-dev/example-nbdev',
                'lib_path': 'example_nbdev'},
  'syms': {'example_nbdev.core': {'example_nbdev.core.foo': ('core.html#foo', 'example_nbdev/core.py')}}}
